[package]
name = "audio"
version = "0.1.0"
edition = "2021"

[dependencies]
alsa = "0.9.0"
claxon = "0.4.3"
wgpu = "0.20.1"
winit = "0.30.3"
log = "0.4.22"
env_logger = "0.11.3"
async-executor = "1.12.0"
futures-lite = "2.3.0"